name: lista_de_la_compra_server
description: A server using Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: 3.9.2

dependencies:

  lista_de_la_compra_backend:
    path: ../lista_de_la_compra_backend


dev_dependencies:
  test: ^1.24.0
